### ISSUE TITLE
'exiftool.exe' is not recognized as an internal command.

### ISSUE THREAD

**Issue by andredavys** [detecttechnologies/Thermal_Image_Analysis#4]
After run `pip install -r requirements.txt`, I tried to run the `thermal_analysis.py` script passing a jpg image as input. But I have the following error:

`'exiftool.exe' is not recognized as an internal command.
Traceback (most recent call last):
  File ".\thermal_analysis.py", line 25, in <module>
    obj = CFlir (flir_image_path,color_map=cv2.COLORMAP_JET)
  File "C:\Users\user\Documents\thermal\Thermal_Image_Analysis\CThermal.py", line 44, in __init__
    self.thermal_np, self.raw_thermal_np, self.meta = self.extract_temperatures()
  File "C:\Users\user\Documents\thermal\Thermal_Image_Analysis\CThermal.py", line 145, in extract_temperatures
    meta = json.loads(meta_json)[0]
  File "C:\Users\user\OneDrive\Documents\Anaconda\envs\enviroment\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\OneDrive\Documents\Anaconda\envs\enviroment\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\OneDrive\Documents\Anaconda\envs\enviroment\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

What exactly happened here?

**Comment by rakshith95** [comment]
Hello @andredavys . Forgot to mention it in the README, but if you're running this on Windows you'll have to do the following:
1. Download _exiftool_ (for your OS) from [here](https://exiftool.org/)
2. Extract '_exiftool(-k).exe_' to the folder where you're running the code from 
3. Rename it to _'exiftool.exe'_

Let me know if this works for you

**Comment by andredavys** [comment]
> Hello @andredavys . Forgot to mention it in the README, but if you're running this on Windows you'll have to do the following:
> 
> 1. Download _exiftool_ (for your OS) from [here](https://exiftool.org/)
> 2. Extract '_exiftool(-k).exe_' to the folder where you're running the code from
> 3. Rename it to _'exiftool.exe'_
> 
> Let me know if this works for you

It's work for me

**Comment by rakshith95** [comment]
Okay thanks for letting us know, closing this issue then
